// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Opnsense
{
    [OpnsenseResourceType("opnsense:index/dhcp_static_map:dhcp_static_map")]
    public partial class Dhcp_static_map : global::Pulumi.CustomResource
    {
        [Output("hostname")]
        public Output<string?> Hostname { get; private set; } = null!;

        [Output("interface")]
        public Output<string> Interface { get; private set; } = null!;

        [Output("ipaddr")]
        public Output<string> Ipaddr { get; private set; } = null!;

        [Output("mac")]
        public Output<string> Mac { get; private set; } = null!;


        /// <summary>
        /// Create a Dhcp_static_map resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Dhcp_static_map(string name, Dhcp_static_mapArgs args, CustomResourceOptions? options = null)
            : base("opnsense:index/dhcp_static_map:dhcp_static_map", name, args ?? new Dhcp_static_mapArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Dhcp_static_map(string name, Input<string> id, Dhcp_static_mapState? state = null, CustomResourceOptions? options = null)
            : base("opnsense:index/dhcp_static_map:dhcp_static_map", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/mj-sakellaropoulos/pulumi-opnsense",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Dhcp_static_map resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Dhcp_static_map Get(string name, Input<string> id, Dhcp_static_mapState? state = null, CustomResourceOptions? options = null)
        {
            return new Dhcp_static_map(name, id, state, options);
        }
    }

    public sealed class Dhcp_static_mapArgs : global::Pulumi.ResourceArgs
    {
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        [Input("interface", required: true)]
        public Input<string> Interface { get; set; } = null!;

        [Input("ipaddr", required: true)]
        public Input<string> Ipaddr { get; set; } = null!;

        [Input("mac", required: true)]
        public Input<string> Mac { get; set; } = null!;

        public Dhcp_static_mapArgs()
        {
        }
        public static new Dhcp_static_mapArgs Empty => new Dhcp_static_mapArgs();
    }

    public sealed class Dhcp_static_mapState : global::Pulumi.ResourceArgs
    {
        [Input("hostname")]
        public Input<string>? Hostname { get; set; }

        [Input("interface")]
        public Input<string>? Interface { get; set; }

        [Input("ipaddr")]
        public Input<string>? Ipaddr { get; set; }

        [Input("mac")]
        public Input<string>? Mac { get; set; }

        public Dhcp_static_mapState()
        {
        }
        public static new Dhcp_static_mapState Empty => new Dhcp_static_mapState();
    }
}
