// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// OPNsense platform user password
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "opnsense:password")
}

// OPNsense platform URI
func GetUri(ctx *pulumi.Context) string {
	return config.Get(ctx, "opnsense:uri")
}

// OPNsense platform user ID
func GetUser(ctx *pulumi.Context) string {
	return config.Get(ctx, "opnsense:user")
}
