# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('opnsense')


class _ExportableConfig(types.ModuleType):
    @property
    def password(self) -> Optional[str]:
        """
        OPNsense platform user password
        """
        return __config__.get('password')

    @property
    def uri(self) -> Optional[str]:
        """
        OPNsense platform URI
        """
        return __config__.get('uri')

    @property
    def user(self) -> Optional[str]:
        """
        OPNsense platform user ID
        """
        return __config__.get('user')

