// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Dhcp_static_map extends pulumi.CustomResource {
    /**
     * Get an existing Dhcp_static_map resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Dhcp_static_mapState, opts?: pulumi.CustomResourceOptions): Dhcp_static_map {
        return new Dhcp_static_map(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'opnsense:index/dhcp_static_map:dhcp_static_map';

    /**
     * Returns true if the given object is an instance of Dhcp_static_map.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Dhcp_static_map {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Dhcp_static_map.__pulumiType;
    }

    public readonly hostname!: pulumi.Output<string | undefined>;
    public readonly interface!: pulumi.Output<string>;
    public readonly ipaddr!: pulumi.Output<string>;
    public readonly mac!: pulumi.Output<string>;

    /**
     * Create a Dhcp_static_map resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: Dhcp_static_mapArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Dhcp_static_mapArgs | Dhcp_static_mapState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Dhcp_static_mapState | undefined;
            resourceInputs["hostname"] = state ? state.hostname : undefined;
            resourceInputs["interface"] = state ? state.interface : undefined;
            resourceInputs["ipaddr"] = state ? state.ipaddr : undefined;
            resourceInputs["mac"] = state ? state.mac : undefined;
        } else {
            const args = argsOrState as Dhcp_static_mapArgs | undefined;
            if ((!args || args.interface === undefined) && !opts.urn) {
                throw new Error("Missing required property 'interface'");
            }
            if ((!args || args.ipaddr === undefined) && !opts.urn) {
                throw new Error("Missing required property 'ipaddr'");
            }
            if ((!args || args.mac === undefined) && !opts.urn) {
                throw new Error("Missing required property 'mac'");
            }
            resourceInputs["hostname"] = args ? args.hostname : undefined;
            resourceInputs["interface"] = args ? args.interface : undefined;
            resourceInputs["ipaddr"] = args ? args.ipaddr : undefined;
            resourceInputs["mac"] = args ? args.mac : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Dhcp_static_map.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering dhcp_static_map resources.
 */
export interface Dhcp_static_mapState {
    hostname?: pulumi.Input<string>;
    interface?: pulumi.Input<string>;
    ipaddr?: pulumi.Input<string>;
    mac?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Dhcp_static_map resource.
 */
export interface Dhcp_static_mapArgs {
    hostname?: pulumi.Input<string>;
    interface: pulumi.Input<string>;
    ipaddr: pulumi.Input<string>;
    mac: pulumi.Input<string>;
}
