// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Dns_host_override extends pulumi.CustomResource {
    /**
     * Get an existing Dns_host_override resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Dns_host_overrideState, opts?: pulumi.CustomResourceOptions): Dns_host_override {
        return new Dns_host_override(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'opnsense:index/dns_host_override:dns_host_override';

    /**
     * Returns true if the given object is an instance of Dns_host_override.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Dns_host_override {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Dns_host_override.__pulumiType;
    }

    public readonly domain!: pulumi.Output<string>;
    public readonly host!: pulumi.Output<string>;
    public readonly ip!: pulumi.Output<string>;
    public readonly type!: pulumi.Output<string>;

    /**
     * Create a Dns_host_override resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: Dns_host_overrideArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Dns_host_overrideArgs | Dns_host_overrideState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Dns_host_overrideState | undefined;
            resourceInputs["domain"] = state ? state.domain : undefined;
            resourceInputs["host"] = state ? state.host : undefined;
            resourceInputs["ip"] = state ? state.ip : undefined;
            resourceInputs["type"] = state ? state.type : undefined;
        } else {
            const args = argsOrState as Dns_host_overrideArgs | undefined;
            if ((!args || args.domain === undefined) && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            if ((!args || args.host === undefined) && !opts.urn) {
                throw new Error("Missing required property 'host'");
            }
            if ((!args || args.ip === undefined) && !opts.urn) {
                throw new Error("Missing required property 'ip'");
            }
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["domain"] = args ? args.domain : undefined;
            resourceInputs["host"] = args ? args.host : undefined;
            resourceInputs["ip"] = args ? args.ip : undefined;
            resourceInputs["type"] = args ? args.type : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Dns_host_override.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering dns_host_override resources.
 */
export interface Dns_host_overrideState {
    domain?: pulumi.Input<string>;
    host?: pulumi.Input<string>;
    ip?: pulumi.Input<string>;
    type?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Dns_host_override resource.
 */
export interface Dns_host_overrideArgs {
    domain: pulumi.Input<string>;
    host: pulumi.Input<string>;
    ip: pulumi.Input<string>;
    type: pulumi.Input<string>;
}
